# все данные вводятся с индексом (начало 0)
[model]
L = [0, 1, 2] # множество звеньев сети
L_k = [[0, 1], [1, 2], [0, 2]] # маршрут для соединений k-класса
K = [0, 1, 2] # множество классов соединений
K_l = [[0, 2], [0, 1], [1, 2]] # множество классов соединений, маршруты которых проходят через l-звено
C = [2, 3, 2] # емкости звеньев
a = [1, 2, 1] # предложенная нагрузка соединений
d = [2, 1, 1] # требование к емкости всех звеньев маршрута соединения k-класса
[solver]
accuracy = 0.1
debug_info = true
